<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionOffer\Block\Cart\Item\Offers;
use Magento\Checkout\Helper\Data;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Offers $block */

/** @var Data $checkoutHelper */
$checkoutHelper = $this->helper(Data::class);

/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $this->helper(\Magento\Catalog\Helper\Data::class);

$appliedOffers = $block->getAppliedOffers();
$availableOffers = $block->getAvailableOffers();
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($appliedOffers): ?>
    <table class="item-offers">
        <?php foreach ($appliedOffers as $appliedOffer): ?>
            <tr class="item-offer">
                <td class="item-offer-name"><?= $appliedOffer['name']; ?></td>
                <td class="item-offer-options">
                    <?php foreach ($appliedOffer['options'] as $option): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option); ?>
                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                        <dd>
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['full_view'], ['span', 'a']); ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']); ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </td>
                <td class="item-offer-price">
                    <?= $escaper->escapeHtml($checkoutHelper->formatPrice($appliedOffer['price']), ['span']); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<div class="actions-toolbar">
    <?= $block->getData('action_html'); ?>
</div>

<?php if ($availableOffers): ?>
    <div class="fieldset catalog-product-option-offers">
        <div class="field">
            <label class="label">
                <span><?= __('Offers'); ?></span>
            </label>
            <div class="control">
                <div class="nested">
                    <?php foreach ($availableOffers as $availableOffer): ?>
                        <?php
                        $offerPrice = $catalogHelper->getTaxPrice(
                            $product,
                            $availableOffer->getPrice(),
                            true
                        );
                        ?>
                        <div class="field choice admin__field admin__field-option product-option-offer">
                            <input type="checkbox" class="checkbox admin__control-checkbox" name="cart[<?= $item->getId(); ?>][offer][]" id="cart-<?= $item->getId(); ?>-offer-<?= $availableOffer->getId(); ?>" value="<?= $availableOffer->getId(); ?>" data-offer-id="<?= $availableOffer->getId(); ?>">
                            <label class="label admin__field-label" for="offer[<?= $availableOffer->getId(); ?>]">
                                <span><?= $availableOffer->getName(); ?></span>
                                <span class="price-notice">
                                    +
                                    <?= $escaper->escapeHtml($checkoutHelper->formatPrice($offerPrice), ['span']); ?>
                                </span>
                            </label>
                            <div class="description"><?= $escaper->escapeHtml($availableOffer->getDescription()); ?></div>
                            <ul class="options">
                                <?php foreach ($block->getOfferOptionNames($availableOffer) as $optionData): ?>
                                    <li><?= $escaper->escapeHtml($optionData['label']); ?><?php if ($optionData['value']): ?>: <?= $escaper->escapeHtml($optionData['value']); ?><?php endif; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
